import type { Metadata } from "next";
import React from 'react'; // Importar explícitamente React
import "./globals.css";
import { Header } from '../components/header/headerComponents';
 
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
