 
export const productos = [
  {
    id: 1,
    nombre: 'Ceviche',
    cantidad_disponible: 50,
    precio: 18.0,
    img: '/img/product/ceviche.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 2,
    nombre: 'Lomo Saltado',
    cantidad_disponible: 30,
    precio: 22.0,
    img: '/img/product/lomo-saltado.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 3,
    nombre: 'Aji de Gallina',
    cantidad_disponible: 25,
    precio: 16.5,
    img: '/img/product/aji-de-gallina.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 4,
    nombre: 'Arroz con Pollo',
    cantidad_disponible: 40,
    precio: 14.0,
    img: '/img/product/arroz-con-pollo.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 5,
    nombre: 'Papa a la Huancaína',
    cantidad_disponible: 50,
    precio: 12.0,
    img: '/img/product/papa-a-la-huancaina.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 6,
    nombre: 'Tacu Tacu',
    cantidad_disponible: 20,
    precio: 15.0,
    img: '/img/product/tacu-tacu.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 7,
    nombre: 'Causa Rellena',
    cantidad_disponible: 30,
    precio: 18.0,
    img: '/img/product/causa-rellena.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 8,
    nombre: 'Chicharrón de Cerdo',
    cantidad_disponible: 35,
    precio: 20.0,
    img: '/img/product/chicharron-cerdo.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 9,
    nombre: 'Tiradito de Pescado',
    cantidad_disponible: 20,
    precio: 17.0,
    img: '/img/product/tiradito-de-pescado.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 10,
    nombre: 'Sopa Seca',
    cantidad_disponible: 25,
    precio: 13.0,
    img: '/img/product/sopa-seca.jpg',
    tipo_producto: 'Comida',
  },
  {
    id: 11,
    nombre: 'Pollo Apanado',
    cantidad_disponible: 30,
    precio: 10.5,
    img: '/img/product/pollo-apanado.jpg',
    tipo_producto: 'Comida',
  }
];